[workspace]
resolver = "2"
members = [
  "arrow-udf",
  "arrow-udf-bench",
  "arrow-udf-example",
  "arrow-udf-flight",
  "arrow-udf-js",
  "arrow-udf-macros",
  "arrow-udf-python",
  "arrow-udf-wasm",
]

[workspace.dependencies]
anyhow = "1"
arrow-arith = "53"
arrow-array = "53"
arrow-buffer = "53"
arrow-cast = "54"
arrow-schema = "53"
arrow-select = "53"
arrow-ipc = "53"
arrow-data = "53"
arrow-flight = "53"
expect-test = "1"
serde_json = "1"
tokio = "1"
